###############################################################################
## @file classes/AUTOTOOLS/register.mk
## @author Y.M. Morgan
## @date 2012/07/13
##
## Register AUTOTOOLS modules.
###############################################################################

# Set also LOCAL_MODULE so that everything works correctly
ifneq ("$(LOCAL_HOST_MODULE)","")
  LOCAL_MODULE := $(LOCAL_HOST_MODULE)
endif

LOCAL_MODULE_CLASS := AUTOTOOLS

LOCAL_MODULE_FILENAME := $(LOCAL_MODULE).done
LOCAL_DONE_FILES += $(LOCAL_MODULE).done

# Compatiblity
LOCAL_ARCHIVE := $(LOCAL_AUTOTOOLS_ARCHIVE)
LOCAL_ARCHIVE_VERSION := $(LOCAL_AUTOTOOLS_VERSION)
LOCAL_ARCHIVE_SUBDIR := $(LOCAL_AUTOTOOLS_SUBDIR)
LOCAL_ARCHIVE_PATCHES := $(LOCAL_AUTOTOOLS_PATCHES)
LOCAL_COPY_TO_BUILD_DIR := $(LOCAL_AUTOTOOLS_COPY_TO_BUILD_DIR)
$(call macro-copy,LOCAL_ARCHIVE_CMD_UNPACK,LOCAL_AUTOTOOLS_CMD_UNPACK)
$(call macro-copy,LOCAL_ARCHIVE_CMD_POST_UNPACK,LOCAL_AUTOTOOLS_CMD_POST_UNPACK)
$(call macro-copy,LOCAL_CMD_CONFIGURE,LOCAL_AUTOTOOLS_CMD_CONFIGURE)
$(call macro-copy,LOCAL_CMD_BUILD,LOCAL_AUTOTOOLS_CMD_BUILD)
$(call macro-copy,LOCAL_CMD_INSTALL,LOCAL_AUTOTOOLS_CMD_INSTALL)
$(call macro-copy,LOCAL_CMD_CLEAN,LOCAL_AUTOTOOLS_CMD_CLEAN)
$(call macro-copy,LOCAL_CMD_POST_CONFIGURE,LOCAL_AUTOTOOLS_CMD_POST_CONFIGURE)
$(call macro-copy,LOCAL_CMD_POST_BUILD,LOCAL_AUTOTOOLS_CMD_POST_BUILD)
$(call macro-copy,LOCAL_CMD_POST_INSTALL,LOCAL_AUTOTOOLS_CMD_POST_INSTALL)
$(call macro-copy,LOCAL_CMD_POST_CLEAN,LOCAL_AUTOTOOLS_CMD_POST_CLEAN)

# Register in the system
$(module-add)
