
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := alsa-lib
LOCAL_MODULE_CLASS := PREBUILT
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libusb
LOCAL_MODULE_CLASS := PREBUILT
include $(BUILD_PREBUILT)

