
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := libpcre

LOCAL_AUTOTOOLS_VERSION := 7.8
LOCAL_AUTOTOOLS_ARCHIVE := pcre3_$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_DIR := pcre-$(LOCAL_AUTOTOOLS_VERSION)

include $(BUILD_AUTOTOOLS)

