
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := wireless_tools

LOCAL_AUTOTOOLS_VERSION := 29
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_MODULE).$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_DIR := $(LOCAL_MODULE).$(LOCAL_AUTOTOOLS_VERSION)

LOCAL_AUTOTOOLS_PATCHES := \
	lucie/wireless_tools.29-android.patch

LOCAL_AUTOTOOLS_MAKE_BUILD_ENV := \
	$(AUTOTOOLS_CONFIGURE_ENV)

LOCAL_AUTOTOOLS_MAKE_BUILD_ARGS := \
	CC=$(TARGET_CC)

LOCAL_AUTOTOOLS_MAKE_INSTALL_ENV := \
	$(AUTOTOOLS_CONFIGURE_ENV)

LOCAL_AUTOTOOLS_MAKE_INSTALL_ARGS := \
	CC=$(TARGET_CC) \
	PREFIX=$(TARGET_OUT_STAGING)

LOCAL_AUTOTOOLS_CMD_CONFIGURE := wirelesss_tools-cmd-configure
LOCAL_AUTOTOOLS_CMD_POST_CLEAN := wirelesss_tools-cmd-post-clean

wirelesss_tools-cmd-configure = $(empty)

wirelesss_tools-cmd-post-clean = $(empty)

include $(BUILD_AUTOTOOLS)

