
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := iptables

LOCAL_AUTOTOOLS_VERSION := 1.4.11.1
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION).tar.bz2
LOCAL_AUTOTOOLS_DIR := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION)

LOCAL_AUTOTOOLS_PATCHES := \
	lucie/iptables-1.4.11.1.patch

LOCAL_AUTOTOOLS_CONFIGURE_ARGS := \
	--sysconfdir=/etc

include $(BUILD_AUTOTOOLS)

