
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := expat

LOCAL_AUTOTOOLS_VERSION := 2.0.1
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_MODULE)_$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_DIR := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION)

include $(BUILD_AUTOTOOLS)

